# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
gas_reports = ["*"]
libs = ["lib"]
out = "out"
verbosity = 3
ffi = true

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4
