# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
libs = ["lib"]
verbosity = 3
ffi = true

remappings = [
    "@prb/test/=lib/prb-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/"
]