# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
libs = ["lib"]
verbosity = 3
ffi = true
evm_version = 'cancun'

remappings = [
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "solady/=lib/solady/src/"
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
arb = "https://arbitrum-mainnet.infura.io/v3/${INFURA_KEY}"