# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
libs = ["lib"]
verbosity = 3
ffi = true
evm_version = 'cancun'
viaIR = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "solady/=lib/solady/src/"
]

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ARBISCAN_KEY}" }
optimism = { key = "${OPTISCAN_KEY}" }
base = { key = "${BASESCAN_KEY}" }


[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_KEY}"
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_KEY}"
base = "https://base-rpc.publicnode.com	"