name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  INFURA_KEY: ${{ secrets.INFURA_KEY }}

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.13'

      - name: Install eth_abi
        run: pip install eth-abi==2.2.0 rlp==2.0.1 web3==5.30.0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install toji
        run: cargo install --git https://github.com/rkdud007/toji --locked --force

      - name: Install deps
        run: forge install

      - name: Run tests
        run: forge test
